#!/bin/bash

set -e

CONTRIB="$(dirname "$(readlink -e "$0")")"
ROOT_FOLDER="$CONTRIB"/..
PACKAGES="$ROOT_FOLDER"/packages/
LOCALE="$ROOT_FOLDER"/qtum_electrum/locale/

if [ ! -d "$LOCALE" ]; then
  echo "Run make_locale first!"
  exit 1
fi

if [ ! -d "$PACKAGES" ]; then
  echo "Run make_packages first!"
  exit 1
fi

(
    cd "$ROOT_FOLDER"

    echo "'git clean -fd' would delete the following files: >>>"
    git clean -fd --dry-run
    echo "<<<"

    python3 setup.py --quiet sdist --format=zip,gztar
)
